export const MOSTRAR_FORMULARIO = 'MOSTRAR_FORMULARIO';
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const AGREGAR_PROYECTOS = 'AGREGAR_PROYECTOS';
export const OBTENER_PROYECTO = 'OBTENER_PROYECTO';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';